export const CHANGE_CART_ITEM_INFO = 'CHANGE_CART_ITEM_INFO';
export const CHANGE_CART_ITEM_CHECK_INFO = 'CHANGE_CART_ITEM_CHECK_INFO';
export const CLEAN_CART_PRODUCT = 'CLEAN_CART_PRODUCT';
export const SET_CART_ITEM_CHECKED = 'SET_CART_ITEM_CHECKED';
export const CHANGE_SHOP_NAME = 'CHANGE_SHOP_NAME';
export const CLEAR_CART_DATA_INFO = 'CLEAR_CART_DATA_INFO';
